<?php
return $keys = [
        'posts'=>'Posts',
        'pages'=>'Pages',
        'galleries'=>'Gallery',
        'mainpage'=>'Main page',

        'undergraduate'=>'Undergraduate',
        'masterdegree'=>'Master Degree',
        'englishprograms'=>'English programs',
        'phd'=>'PhD',
        'chair'=>'Chair',
        'mainbanner'=>'Main page banner',
        'mainfeatures'=>'Main page features',
        'certificate'=>'Certificate',
        'feedback'=>'Testimonials',
        'camp'=>'Campuses',
        'post'=>'News & Events',
        'graduate'=>'Graduate',
        'faq'=>'F.A.Q',
        'expeditions'=>'Expeditions',
        'gallery'=>'Photo Gallery',
        'video'=>'Video Gallery',
        'vacancy'=>'Vacancy',
        'settings'=>'Settings',
        'langwords'=>'Lang words',
        'examples'=>'Examples',
        'admin'=>'Admins',
];
